### ISSUE TITLE
Can't build 1.1.2 from source due to JSqlParser 1.3-SNAPSHOT dependency

### ISSUE THREAD

**Issue by O1O1O1O** [olavloite/spanner-jdbc#118]
If I try to build from source (master or 1.1.2 version) it fails because the JSqlParser 1.3-SNAPSHOT dependency is missing.  As best I can tell only 1.2 is in the Maven repos so far.  
```
mvn install -DskipITs
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< nl.topicus:spanner-jdbc >-----------------------
[INFO] Building spanner-jdbc 1.1.2
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for com.github.jsqlparser:jsqlparser:jar:1.3-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.602 s
[INFO] Finished at: 2018-09-26T13:52:56-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spanner-jdbc: Could not resolve dependencies for project nl.topicus:spanner-jdbc:jar:1.1.2: Could not find artifact com.github.jsqlparser:jsqlparser:jar:1.3-SNAPSHOT -> [Help 1]
```
Using 1.2 in the pom.xml allows the build but tests fail.

**Comment by olavloite** [comment]
I realize that I haven't updated the build instructions yet... You need to checkout my fork of JSqlParser as well and reference this fork in your workspace in order to build the driver from source. I have made a couple of fixes for the parser, but these have not yet been included in a new version of JSqlParser.
My fork can be found here: https://github.com/olavloite/JSqlParser

I have submitted PR's for the fixes to JSqlParser as well, but these have not yet been included in the parser (or released in a new version). These PR's are:
* https://github.com/JSQLParser/JSqlParser/pull/659
* https://github.com/JSQLParser/JSqlParser/pull/653
* https://github.com/JSQLParser/JSqlParser/pull/651
