### ISSUE TITLE
Can you batch DDL statements?

### ISSUE THREAD

**Issue by shlomiw** [olavloite/spanner-jdbc#15]
Hi,

Online schema changes are very slow, see:
https://stackoverflow.com/questions/45592518/online-update-spanner-schema-is-extremely-slow

They suggested batching them, and it is actually much faster.

Is it possible to batch DDL statements?

Thanks!

**Comment by olavloite** [comment]
Instead of batching DDL-statements, it has now been made possible to run DDL-statements asynchronously. This gives better support in standard tools like DBeaver, as these do not normally batch multiple statements.
DDL-statements are still by default ran synchronously. In order to enable async execution, you must set the property AsyncDdlOperations=true. This can be done as a connection property or part of the connection URL, or you can switch it on and off dynamically using the following special command (enter it in for example DBeaver):
`SET_CONNECTION_PROPERTY AsyncDdlOperations=true`

To monitor the progress of async DDL-operations you can use the following two special commands:
`SHOW_DDL_OPERATIONS`
`CLEAN_DDL_OPERATIONS`

The latter command will remove all DDL-operations that have finished from the local session cache.
Running the following sequence of statements in async mode will work:
`
create table number (id int64 not null, name string(100)) primary key (id);
alter table number add is_prime bool;
create index idx_number_is_prime on number (is_prime);
`

**Comment by shlomiw** [comment]
Ok, I'll try that.
In the sequence of the commands you wrote - It looks like it respects the dependency order of the DDL commands.

Thanks!

**Comment by olavloite** [comment]
Async DDL-operations work, but do not give the performance gain I would have expected. I have therefore decided to also add the possibility of batching DDL statements (and these batches could then also be run asynchronously).

**Comment by olavloite** [comment]
I have tested the three different options (batching, sequential execution and asynchronous execution) with these statements (the initial state of the database was equal in all cases, i.e. the tables were present):

```
drop table test1;
drop table test2;
drop table test3;

create table test1 (id int64 not null, name string(100)) primary key (id);
create table test2 (id int64 not null, name string(100)) primary key (id);
create table test3 (id int64 not null, name string(100)) primary key (id);

```
The results were as follows:
Batched: 20668ms
Sequential: 228140ms
Asynchronous: 66434ms

**Comment by olavloite** [comment]
Batching also added for version 0.21.

**Comment by shlomiw** [comment]
Great!
How do you batch the statements? I.e. via DBeaver?
Thanks! Really appreciate your work!

**Comment by olavloite** [comment]
@shlomiw I just released version 0.22 with support for Flyway. This version also includes support for 'auto batching' of DDL statements.
DBeaver does not batch multiple statements in a script (i.e. does not call statement.addBatch(String sql) and then statement.executeBatch()), but calls statement.execute(String sql) for each sql statement. You can circumvent this by using AutoBatchDdlOperations. Have a look at this page for an example: https://github.com/olavloite/spanner-jdbc/wiki/DDL-statements,-Batching-and-Async-Execution

**Comment by shlomiw** [comment]
@olavloite - once again - great work! will let you know if I see any issue.
Thanks!!

**Comment by shlomiw** [comment]
I've tested it and it's working great! 👍

**Comment by shlomiw** [comment]
Wanted to said thanks again! I'm using it all the time and it works perfectly.
