### ISSUE TITLE
unable to properly get Parameter Type Name for parameters in Delete statement

### ISSUE THREAD

**Issue by jpoernomoatsafe** [olavloite/spanner-jdbc#17]
```
// Table schema as follows:
// CREATE TABLE `MY_TABLE` (`MYID` int64, `NAME` string(200)) PRIMARY KEY (MYID)
CloudSpannerConection connection = getCloudSpannerConnection();
String sql = "DELETE FROM `MY_TABLE` WHERE `MY_ID` = ?"
PreparedStatement statement = connection.prepareStatement(sql);
ParameterMetaData pmd = statement.getParameterMetaData();
String typeName = pmd.getParameterTypeName(1);
```

Result: 
typeName is "Other"

Expected:
typeName is "INT64"

If we changed the sql string to 
```
"INSERT INTO 'MY_TABLE' ('MYID', 'NAME') VALUES (?, ?)"
```
it would properly recognize the first parameter as INT64

issue discovered on v0.19, but I think it's been in the code as early as v0.9

**Comment by olavloite** [comment]
The problem was caused by the fact that Cloud Spanner does not actually need the column name of a key value when deleting a record. Instead, Cloud Spanner expects a delete call containing only the key values in the column definition order, without the column name. This caused the meta data to be lost. It has been fixed for version 0.20.
