### ISSUE TITLE
 "Column not found in table" happens even though there is a column

### ISSUE THREAD

**Issue by jkhnn** [olavloite/spanner-jdbc#22]
Hello, olavloite
Thank you for providing useful library.

After building with maven, I specified the jar with Pyspark submit and executed the job. 
The following is the program.

```
  fields = [
      StructField('date', StringType(), True),
・・・・
      StructField('aaa', StringType(), True)
  ]
  sdf = spark.createDataFrame(rdd, StructType(fields))
  url = 'jdbc:cloudspanner://localhost;Instance=ins-sample;Database=db-sample'
  table = "test_table"
  mode = "append"
  properties = {"driver": "nl.topicus.jdbc.CloudSpannerDriver"}
  sdf.write.jdbc(url=url, table=table, mode=mode, properties=properties)
```

Such an error came out.

```
18/02/06 16:25:10 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 6.0 in stage 5.0
 (TID 6069, xxxxxxxxxxx.internal, executor 51):
 nl.topicus.jdbc.exception.CloudSpannerSQLException: COMMIT failed: NOT_FOUND: nl.topicus.jdbc.shaded.io.grpc.StatusRuntimeException: NOT_FOUND: Column not found in table test_table: "date"
resource_type: "spanner.googleapis.com/Column"
resource_name: "\" date \ ""
```

Dataframe has a column called "date". Does that mean that "\" is additionally included?
I am sorry to hear that you are busy, but please tell me.

**Comment by olavloite** [comment]
The double quotes (") are added automatically by Spark as it expects double quotes to be the default way to quote table and column names. Cloud Spanner does however use backticks ( ` ) for quoting: [https://cloud.google.com/spanner/docs/lexical#identifiers](https://cloud.google.com/spanner/docs/lexical#identifiers)
In order to circumvent this problem in Spark, you need to register a custom dialect that specifies backticks for quoting. See here for an example on how to do that in Java: [http://www.googlecloudspanner.com/2017/10/google-cloud-spanner-with-apache-spark.html](http://www.googlecloudspanner.com/2017/10/google-cloud-spanner-with-apache-spark.html)

I'm not very experienced with Python, so I'm not sure how to register a custom dialect for Spark in Python, but you could have a look at this question on StackOverflow: [https://stackoverflow.com/questions/41767151/dsx-pyspark-writing-data-to-dashdb-with-custom-jdbc-dialect?rq=1](https://stackoverflow.com/questions/41767151/dsx-pyspark-writing-data-to-dashdb-with-custom-jdbc-dialect?rq=1)
