### ISSUE TITLE
Problem @OrderColumn in OneToMany Relationship

### ISSUE THREAD

**Issue by arduitoProject** [olavloite/spanner-jdbc#29]
We have a new problem using spanner-jdbc and spanner-hibernate in our Spring Boot project:

Caused by: nl.topicus.jdbc.shaded.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: No parameter found for binding: p1
	at nl.topicus.jdbc.shaded.io.grpc.Status.asRuntimeException(Status.java:526) ~[spanner-jdbc-0.25.jar:na]
	... 19 common frames omitted

This exception happens when we use the annotation 
@OrderColumn(name = "phone_order")  
in a OneToMany (with join) relationship.

In our [example](https://gist.github.com/arduitoProject/a694b57d505a019225e0d7ecbddbc058) the create is ok, but fail in update.

The complete example is [here](https://github.com/arduitoProject/spanner-jpa-example.git).

**Comment by olavloite** [comment]
I'm working on a solution, but it's a little bit harder than I first thought, as the query that is generated by Hibernate in this case actually does an update of one of the fields of the primary key. That is not possible on Cloud Spanner, but the update doesn't actually change the value, it only sets the same value as it already was (i.e. something like update emp_phone set employee_id=2, phone_id=1 where phone_id=1 and phone_order=2)

**Comment by olavloite** [comment]
There are actually three problems here, one which is insolvable and two that are easy to solve:
1. It is impossible to update a column that is part of the primary key in Cloud Spanner. The only way to 'change' (a part) of the value of the primary key, is to delete the entire row and re-insert it with a different key value.
1. The error message you were getting is not very helpful. I've added some checks that will make the driver return a decent error message telling you that columns that are part of the primary key cannot be updated.
1. The reason that Hibernate is generating this query that is not supported by Cloud Spanner, is because your data model does not match your meta model. The primary key on the table emp_phone should consist of (employee_id, phone_order) and NOT (employee_id, phone_id). If you let Hibernate generate the datamodel for you, you will see that the data model will be generated like this:

```sql
create table emp_phone (employee_id STRING(255) not null, phone_id STRING(255) not null, phone_order INT64 not null, primary key (employee_id, phone_order))
create table employee (employee_id STRING(255) not null, lastname STRING(255), name STRING(255), primary key (employee_id))
create table phone (phone_id STRING(255) not null, nro_tel INT64, primary key (phone_id))
create unique index UK_b2l8k66395hhe0ltqys53lal on emp_phone (phone_id)
```

If you use that data model, your sample application will also run without any problems.

**Comment by ptamburro** [comment]
We changed the scheme and effectively the sample code works well. But our real code still shows the exception, even though we changed the scheme. The only difference is that the entity "Employee" is the daughter of another entity, leaving a composite key for the relationship.

this is our real model:

CREATE TABLE searchers_geolocations_points (
	account_id STRING(MAX) NOT NULL,
	geo_order INT64,
	searcher_id STRING(MAX) NOT NULL,
	geoloc_id STRING(MAX) NOT NULL,
) PRIMARY KEY (account_id, searcher_id, geo_order)

therefore, modifying the model, I get the same error

Caused by: nl.topicus.jdbc.shaded.io.grpc.StatusRuntimeException: INVALID_ARGUMENT: No matching signature for operator = for argument types: STRING, BOOL. Supported signature: ANY = ANY [at 1:188]
...FROM `searchers_geolocations_points` WHERE account_id = @p1 AND searcher_i...

**Comment by olavloite** [comment]
I have forked your example project and edited it to use a composite primary key on the table Employee, and it does work: https://github.com/olavloite/spanner-jpa-example-1

It is of course important that your data model actually is in sync with your class model. As already mentioned, updating one of the values of the primary key is not allowed in a Google Cloud Spanner database.
JPA / Hibernate however should not update any of your primary key values as long as your class model and annotations represent your data model correctly.

1. In the modified example the Employee entity now has a composite primary key consisting of two String values. Both are annotated with an @Id annotation and their values are not updated when updating an Employee.
1. In the @JoinTable annotation for the list of phones, both id columns are included.

Please check in your real code that:
1. All columns included in the primary key are actually annotated with @Id in your Java code
1. All primary key columns are included in the list of join columns in your @JoinTable annotation

If this still does not solve your problem, then please supply an example project where this error occurs.

**Comment by ptamburro** [comment]
Indeed, we had a small error in the class model.
I add a different example with a composite key:
[github](https://github.com/arduitoProject/spanner-jpa-example/releases/tag/v1.1)

the example is based on [hibernate-composite-aggregated](http://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#identifiers-composite-aggregated)

Thank for everything!
