### ISSUE TITLE
support "real" oauth authentication

### ISSUE THREAD

**Issue by ravenAtSafe** [olavloite/spanner-jdbc#6]
I know the .json key file method of authentication matches what the official driver does, but it would be great if we could instead provide an access token (which we would acquire through our own connection management) that was then sent along with each request.  (I'm 75% sure what we want to provide is an access token, but I can confirm if there are any doubts).

https://cloud.google.com/spanner/docs/api-parameters

Maybe the key file is already being converted into an access token?  If so, this would be less work than I fear.

**Comment by olavloite** [comment]
As of version 0.6 I have added the possibility of passing a parameter OAuthAccessToken when opening a new connection. However, this token will never be refreshed, meaning that the specified token must never expire, or the connection must be closed before the token expires. Otherwise, the connection will become invalid when the token expires.

**Comment by olavloite** [comment]
@ravenAtSafe Could you please test if this is actually what you want?

**Comment by ravenAtSafe** [comment]
Sorry for the delayed response but I've spent the last week fighting fires.  Hopefully I'll be able to get you an answer in the next week or two though.  Thanks!

**Comment by ravenAtSafe** [comment]
I can confirm that the `OAuthAccessToken` parameter is working exactly as we had hoped.  No more key files!
