### ISSUE TITLE
DELETE fails when part of the composite key has null value

### ISSUE THREAD

**Issue by jobinba** [olavloite/spanner-jdbc#68]
DELETE statement results in  this exception: 
Exception in thread "main" nl.topicus.jdbc.exception.CloudSpannerSQLException: No value supplied for key column {Column Name}. All key columns must be specified in the WHERE-clause of a DELETE-statement.
	at nl.topicus.jdbc.statement.DeleteKeyBuilder.getKeyBuilder(DeleteKeyBuilder.java:53)
	atnl.topicus.jdbc.statement.CloudSpannerPreparedStatement.createDeleteMutation(CloudSpannerPreparedStatement.java:512)

It happens because composite primary key has column with null value

**Comment by olavloite** [comment]
This issue is somewhat questionable if you look at the SQL standard in its purest form. The query in this case is something like `DELETE FROM FOO WHERE ID1=1 AND ID2=Null`. Formally, `Null=Null` should always return false. Cloud Spanner handles null values in a different way and considers two null values to be equal. This also applies when a null value is allowed in a primary key. I have therefore changed the specific part of the code to allow these queries to be parsed and sent to Cloud Spanner, as Cloud Spanner will also do a correct comparison when handed a key value containing a null value.

Fixed in version 1.0.8

**Comment by olavloite** [comment]
Released 1.0.8
